name: 'GitHub Actions CI - GCP Key 방식'

on:
  push:
    branches:
      - master   # 원하는 브랜치명으로 변경 가능
  workflow_dispatch:

env:
  PROJECT_ID: 'graceful-chain-457201-j3'
  REGION: 'asia-northeast3'
  REPO: 'argo'
  SERVICE: 'portal'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker for GAR
        uses: docker/login-action@v3
        with:
          registry: '${{ env.REGION }}-docker.pkg.dev'
          username: _json_key
          password: '${{ secrets.GCP_SA_KEY }}'

      - name: Set Docker image tag (short SHA)
        id: get_version
        run: echo "VERSION=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and Push Container
        run: |
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.SERVICE }}:${{ steps.get_version.outputs.VERSION }}"
          echo "Docker tag: $DOCKER_TAG"
          docker build --tag "$DOCKER_TAG" .
          docker push "$DOCKER_TAG"
